name: Node.js CI

on: ['push', 'pull_request']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install deps and build (with cache)
        run: pnpm install

      # - name: Lint
      #   run: npm run lint

      - name: Test
        run: npm run test

      - name: Coverage
        run: npm run coverage

      - name: Build
        run: npm run build
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./coverage/lcov.info
