name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Install deps and build (with cache)
        run: pnpm install
      - run: pnpm run build
      - uses: changesets/action@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          version: pnpm run ci:version
          publish: pnpm run ci:publish
          commit: '[ci] release'
          title: '[ci] release'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
